# Generated by Django 4.1.7 on 2023-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tasks_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
