# Generated by Django 4.1.7 on 2023-05-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_added_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='session_id',
            new_name='user_id',
        ),
    ]
